version: "3.1"

services:
  db:
    image: mariadb
    container_name: labs1-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: lo_tst
    volumes:
      - ./db/maria_data:/var/lib/mysql:Z
    networks:
      - net_labs1
    ports:
      - "3306:3306"

  mongo:
    image: mongo
    container_name: labs1-mongodb
    restart: always
    networks:
      - net_labs1
    volumes:
      - ./db/mongo_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: labs1-mongo-express
    networks:
      - net_labs1
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  adminer:
    image: adminer
    restart: always
    networks:
      - net_labs1
    ports:
      - 8091:8080

volumes:
  mongo_data:
    driver: local
  maria_data:
    driver: local

networks:
  net_labs1:
    driver: bridge
